repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.5.0'
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: end-of-file-fixer
    - id: mixed-line-ending
- repo: https://github.com/psf/black
  rev: '23.12.1'
  hooks:
    - id: black
      args: [--line-length=100,--skip-magic-trailing-comma,--safe,--target-version=py38]
- repo: https://github.com/MarketSquare/robotframework-tidy
  rev: '4.7.0'
  hooks:
    - id: robotidy
