version: '3'

services:
  mysql:
    image: mysql:8.2
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: juhavdph_snowdog
      MYSQL_USER: juhavdph_snowdog
      MYSQL_PASSWORD: snowdogSalasana
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  apache:
    image: php:8.3-apache
    container_name: apache-container
    volumes:
      - ./web_app:/var/www/html/snowdog
    environment:
      - SQL_SERVER=mysql-container
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    ports:
      - "8080:80"
    networks:
      - mynetwork
    depends_on:
      - mysql
  
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
    - "8883:8883"
    networks:
      - mynetwork

  nmea-simulator:
    build:
      context: .
      dockerfile: Dockerfile.snowdog_simulator
    depends_on:
      - mqtt-broker
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
